# Cloud Build CI/CD configuration for etude-rag2
# Triggers: Push to main branch or manual trigger

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: etude-rag2-api
  _ENVIRONMENT: dev

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Run tests
  - name: python:3.12-slim
    id: test
    entrypoint: bash
    args:
      - -c
      - |
        pip install uv
        uv sync --frozen
        uv run pytest -v --tb=short
    waitFor: ["-"]

  # Step 2: Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - -f
      - Dockerfile
      - .
    waitFor: [test]

  # Step 3: Push Docker image
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
    waitFor: [build]

  # Step 4: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}-${_ENVIRONMENT}
      - --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --quiet
    waitFor: [push]

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest

timeout: 1800s
