#!/bin/bash
# setup-gcp-project.sh
#
# Google Cloud プロジェクトの作成と初期設定を行うスクリプト
# Terraform 実行前に一度だけ実行してください
#
# Usage:
#   ./scripts/setup-gcp-project.sh <project-id> [billing-account-id]
#
# Example:
#   ./scripts/setup-gcp-project.sh my-etude-rag2-project
#   ./scripts/setup-gcp-project.sh my-etude-rag2-project 012345-ABCDEF-GHIJKL

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions
info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Check arguments
if [ -z "$1" ]; then
    echo "Usage: $0 <project-id> [billing-account-id]"
    echo ""
    echo "Arguments:"
    echo "  project-id         GCP project ID (must be globally unique)"
    echo "  billing-account-id Billing account ID (optional, can be set later)"
    echo ""
    echo "Example:"
    echo "  $0 my-etude-rag2-dev"
    echo "  $0 my-etude-rag2-dev 012345-ABCDEF-GHIJKL"
    exit 1
fi

PROJECT_ID="$1"
BILLING_ACCOUNT="$2"

# Verify gcloud is installed
if ! command -v gcloud &> /dev/null; then
    error "gcloud CLI is not installed. Please install it first: https://cloud.google.com/sdk/docs/install"
fi

# Verify user is authenticated
info "Checking gcloud authentication..."
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1 > /dev/null 2>&1; then
    error "Not authenticated. Please run: gcloud auth login"
fi

ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1)
info "Authenticated as: $ACTIVE_ACCOUNT"

# Check if project already exists
info "Checking if project '$PROJECT_ID' exists..."
if gcloud projects describe "$PROJECT_ID" > /dev/null 2>&1; then
    warn "Project '$PROJECT_ID' already exists."
    read -p "Do you want to continue with the existing project? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
else
    # Create the project
    info "Creating project '$PROJECT_ID'..."
    gcloud projects create "$PROJECT_ID" --name="etude-rag2"
    info "Project created successfully!"
fi

# Set as current project
info "Setting '$PROJECT_ID' as the current project..."
gcloud config set project "$PROJECT_ID"

# Link billing account if provided
if [ -n "$BILLING_ACCOUNT" ]; then
    info "Linking billing account '$BILLING_ACCOUNT'..."
    gcloud billing projects link "$PROJECT_ID" --billing-account="$BILLING_ACCOUNT"
    info "Billing account linked successfully!"
else
    warn "No billing account specified."
    echo ""
    echo "To enable APIs and create resources, you need to link a billing account."
    echo "You can do this manually:"
    echo "  1. Go to: https://console.cloud.google.com/billing/linkedaccount?project=$PROJECT_ID"
    echo "  2. Or run: gcloud billing projects link $PROJECT_ID --billing-account=YOUR_BILLING_ACCOUNT_ID"
    echo ""
    echo "To list your billing accounts:"
    echo "  gcloud billing accounts list"
    echo ""
    read -p "Do you want to continue without billing? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

# Enable essential APIs (subset that don't require billing)
info "Enabling essential APIs..."

# These APIs are needed before Terraform can run
ESSENTIAL_APIS=(
    "cloudresourcemanager.googleapis.com"
    "serviceusage.googleapis.com"
    "iam.googleapis.com"
    "servicenetworking.googleapis.com"
)

for api in "${ESSENTIAL_APIS[@]}"; do
    info "  Enabling $api..."
    gcloud services enable "$api" --project="$PROJECT_ID" 2>/dev/null || warn "  Could not enable $api (may require billing)"
done

# Set up Application Default Credentials
info "Setting up Application Default Credentials..."
if [ ! -f "$HOME/.config/gcloud/application_default_credentials.json" ]; then
    warn "Application Default Credentials not found."
    echo "Running: gcloud auth application-default login"
    gcloud auth application-default login
else
    info "Application Default Credentials already configured."
fi

# Create terraform.tfvars template
TERRAFORM_DIR="$(dirname "$0")/../terraform"
TFVARS_FILE="$TERRAFORM_DIR/terraform.tfvars"

if [ ! -f "$TFVARS_FILE" ]; then
    info "Creating terraform.tfvars template..."
    cat > "$TFVARS_FILE" << EOF
# Generated by setup-gcp-project.sh
# Please review and customize these values

# Required settings
project_id       = "$PROJECT_ID"
github_repo      = "your-org/etude-rag2"  # TODO: Update this
target_folder_id = "your-drive-folder-id"  # TODO: Update this
my_email         = "$ACTIVE_ACCOUNT"

# Optional settings (defaults are usually fine)
# region      = "us-central1"
# environment = "dev"
# db_tier     = "db-f1-micro"
EOF
    info "Created $TFVARS_FILE - please review and update TODO items"
else
    warn "terraform.tfvars already exists, skipping creation"
fi

# Summary
echo ""
echo "=========================================="
echo -e "${GREEN}Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Project ID: $PROJECT_ID"
echo "Active Account: $ACTIVE_ACCOUNT"
echo ""
echo "Next steps:"
echo ""
echo "1. Ensure billing is linked (if not already):"
echo "   gcloud billing projects link $PROJECT_ID --billing-account=YOUR_BILLING_ACCOUNT"
echo ""
echo "2. Review and update terraform/terraform.tfvars:"
echo "   - github_repo: Your GitHub repository"
echo "   - target_folder_id: Google Drive folder ID"
echo ""
echo "3. Run Terraform to create infrastructure:"
echo "   cd terraform"
echo "   terraform init"
echo "   terraform plan"
echo "   terraform apply"
echo ""
echo "4. After Terraform, generate local .env:"
echo "   ./scripts/sync-env-from-secrets.sh dev"
echo ""
